version: '3'
services:
  codepush-redis:
    image: redis:7.2.3
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
  codepush-db:
    platform: linux/x86_64
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-network
  codepush-go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - SERVER_CONFIG=${SERVER_CONFIG}
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT}:8080"
    volumes:
      - ./bundles:/server/bundles
    networks:
      - my-network
    depends_on:
      codepush-db:
        condition: service_healthy
networks:
  my-network:
    driver: bridge
volumes:
  redisdata:

